"""
Standard Error Codes for the Liveness SDK.
"""

FACE_NOT_DETECTED = "FACE_NOT_DETECTED"
FACE_TOO_SMALL = "FACE_TOO_SMALL"
LANDMARKS_UNSTABLE = "LANDMARKS_UNSTABLE"
FRAME_STALLED = "FRAME_STALLED"
TIMEOUT = "TIMEOUT"
CHALLENGE_NOT_COMPLETED = "CHALLENGE_NOT_COMPLETED"
PASSIVE_SPOOF_DETECTED = "PASSIVE_SPOOF_DETECTED"
